nutriProject/upload/urls.py
from django.urls import path, include
from upload.views import UploadView, notice_delete_view, UploadTempView, UploadResultView, UploadDetailView, \
    UploadResultListView
from django.conf import settings
from django.conf.urls.static import static

#해당 네임에서 url patterns에 있는 name의 url로 가주세요~!
app_name = "upload"

urlpatterns = [
    path('', UploadView.as_view(), name='main'), #upload
    path('detail/<slug:eaten_dt>', UploadResultView.as_view(), name='detail'),
    path('detail/info/<int:pk>',UploadDetailView.as_view(), name='detail_info'),
    path('temp/<int:pk>/delete/',notice_delete_view, name='delete'),
    path('temp/<int:pk>',UploadTempView.as_view(), name='temp'),
    path('list/',UploadResultListView.as_view(), name='list'),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nutriProject/upload/templates/upload/info.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
    <!-- Section-->
    <section id="info-page">
        <div class="main-text">
            <h2 class="display-5 fw-bolder">{{ result.created_at | date:"m월d일"}}</h2>
            <h4 class="display-5" id="meal">{{ result.mealtimes }}</h4>
            <span class="small">*해당 영양정보는 1인분 기준의 표준정보이며, 음식양과 레시피에 따라 차이가 발생할 수 있습니다. </span>
        </div>
        <section class="">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0 info-image" src="{{ result.image.url }}" alt="..." /></div>
                    <div class="col-md-6 personal">
                        <div class="card mb-3">
                            <h2 class="card-header fw-bolder">영양성분</h2>
                            <div class="card-body">
                                <h3 class="card-title">'{{ food|join:", " }}'</h3>

                            </div>
                            <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                                <div class="align-items-center">
                                    <table class="table small">
                                        <thead>
                                        <tr>
                                            <th scope="col"></th>
                                            <th scope="col">{{ date.eaten_dt | date:"m월d일"}} 섭취량</th>
                                            <th scope="col">일일 기준</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr class="table-primary">
                                            <th scope="row">칼로리(kcal)</th>
                                            <td>{{ total_cal|floatformat:2}}</td>
                                            <td>{{ cal_rate }}%</td>
                                        </tr>
                                        </tbody>
                                        <tbody>
                                        <tr class="">
                                            <th scope="row">탄수화물(g)</th>
                                            <td>{{ total_carb|floatformat:2 }}</td>
                                            <td>{{ carb_rate }}%</td>
                                        </tr>
                                        </tbody>
                                        <tbody>
                                        <tr class="">
                                            <th scope="row">단백질(g)</th>
                                            <td>{{ total_prot|floatformat:2 }}</td>
                                            <td>{{ prot_rate }}%</td>
                                        </tr>
                                        </tbody>
                                        <tbody>
                                        <tr class="">
                                            <th scope="row">지방(g)</th>
                                            <td>{{ total_fat|floatformat:2 }}</td>
                                            <td>{{ fat_rate }}%</td>
                                        </tr>
                                        </tbody>
                                        <tbody>
                                        <tr class="">
                                            <th scope="row">나트륨(mg)</th>
                                            <td>{{ total_sodium|floatformat:2 }}</td>
                                            <td>{{ sodium_rate }}%</td>
                                        </tr>
                                        </tbody>
                                    </table>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>
            </div>
            <div class="space">

            </div>
        </section>


        <script src="{% static 'js/upload.js' %}"></script>
        <script>


            const meal = document.querySelector('#meal');
            const mealText = meal.innerHTML;

            function changeMealtime () {
                if (mealText == 1){
                    meal.innerHTML = "아침 식사 정보";
                } else if (mealText == 2) {
                    meal.innerHTML = "점심 식사 정보";
                } else if (mealText == 3) {
                    meal.innerHTML = "저녁 식사 정보";
                }
            };
            changeMealtime()

        </script>
    </section>
{% endblock %}

nutriProject/upload/templates/upload/list.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
    <div id="list_form">
        <div class="card-body p-4">
            <div class="row">
                <div class="col-12">

                    <ul class="list-group">
                        {% for i in eaten_dt %}
                            <li class="food-list list-group-item list-group-item-action d-flex justify-content-between align-items-center" >
                                <a style="text-decoration: none;" href="{% url 'upload:detail' eaten_dt=i.eaten_dt|date:"Y-m-d" %}" class="list-group-item-action">{{ i.eaten_dt }}</a>
                                <span class="badge bg-warning">...</span>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

{%  endblock %}

nutriProject/upload/templates/upload/main.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
    <!-- Section-->
    <section id="main_upload-page">
        <div class="main-text">
            <h2 class="display-5 fw-bolder">사진을 업로드 해주세요!</h2>
            <h4 class="display-5">Please upload your pic!</h4>
        </div>
        <form action="{% url 'upload:main' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="img-container">
                <div class="wrapper">
                    <div class="image">
                        <img src='' onerror="this.style.display='none'" alt='' />
                    </div>
                    <div class="content">
                        <div class="file-icon"><i class="fas fa-cloud-upload-alt"></i></div>
                        <div class="file-inner_text">No file chosen, yet!</div>
                    </div>
                    <div id="img-cancle"><i class="fas fa-times"></i></div>
                    <div id="img-name">File name here</div>
                </div>
                <button onclick ="defaultBtnActive()" id="custom-btn" class="btn btn-dark">Choose a file</button>
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary mt-8" id="custom-btn" value="next">
            </div>
        </form>
        <script src="{% static 'js/upload.js' %}"></script>

    </section>
{% endblock %}

<!--
<div class="form-group">
<input type="file" hidden name="image" accept="image/*" class="form-control-file" title="" required="" id="default-btn">
<button onclick ="defaultBtnActive()" id="custom-btn" class="btn btn-dark">Choose a file</button>
</div>
<label for="exampleSelect1" class="form-label5" placeholder="Meal Times"></label> -->

nutriProject/upload/templates/upload/temp.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
    <!-- Section-->
    <section>
        <div class="main-text">
            <h2 class="display-5 fw-bolder">{{ data.created_at | date:"m월d일"}}</h2>
            <h4 class="display-5 meal"> {{ data.mealtimes }} 식사 영양정보</h4>
        </div>
        <form action="{% url 'upload:temp' pk=data.pk %}" method="post" enctype="multipart/form-data">

            {% csrf_token %}
            <div class="img-container">
                <div class="wrapper">
                    <div class="image">
                        <img src='{{ data.image.url }}' alt='' />
                    </div>
                    <div id="img-name">File name here</div>
                </div>
                <button type="button" id="custom-btn" class="btn btn-dark openModalBtn">
                    REPOST
                </button>
                <!-- 모달 영역 -->
                <div id="modalBox" class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="myModalLabel">Information</h4>
                            </div>
                            <div class="modal-body">
                                메인페이지로 돌아갑니다.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary"  onclick="delete_modal()" >확인</button>
                                <button type="button" class="btn btn-default" id="closeModalBtn">취소</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="alert alert-dismissible alert-primary">
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    <strong>Choose!</strong> date to eat! & how many servings!
                </div>
                <!-- 먹을 날짜 선택 -->
                {% bootstrap_form date %}

                <!-- 음식 몇인분? 선택 -->
                {% if food %}
                    {% for i in food %}
                        <div class="accordion">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading{{ forloop.counter }}">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}" aria-expanded="false" aria-controls="collapse{{ forloop.counter }}">
                                    <strong>{{ i }}</strong>
                                </button>
                            </h2>
                            <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse" aria-labelledby="heading{{ forloop.counter }}" data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <fieldset class="form-group">
                                        <h5 class="mt-4">How many servings did you eat?</h5>
                                        <div id="serve_number" >
                                            {% bootstrap_form serve %}
                                        </div>
                                    </fieldset>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}

                <input type="submit" class="btn btn-primary mt-8" id="custom-btn" value="upload">
                </div>
        </form>
        <script src="{% static 'js/upload.js' %}"></script>
        <script>
            $('.bagde').ready(function() {
                const meal = document.getElementsByClassName('meal');
                const text = '식사 영양 정보'
                if (meal) {
                    meal[0].textContent = '아침' + text;
                    meal[1].textContent = '점심' + text;
                    meal[2].textContent = '저녁' + text;
                } else {
                    return;
                }
            });
            // 모달 버튼에 이벤트를 건다.
            $('.openModalBtn').on('click', function(){
                $('#modalBox').modal('show');
            });
            // 모달 안의 취소 버튼에 이벤트를 건다.
            $('#closeModalBtn').on('click', function(){
                $('#modalBox').modal('hide');
            });
            function delete_modal() {
                location.replace('/temp/{{ data.pk }}/delete/');
            }

            const eatenForm =document.getElementById('id_eaten_dt');

            eatenForm.value = '{{ data.created_at|date:"Y-m-d" }}'
                //new Date().toISOString().substring(0, 10);

        </script>

    </section>
{% endblock %}